name: examples

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: nix-on-debian:latest
    steps:
      - uses: actions/checkout@v1
      - name: First run of nix-shell to measure download time
        run: nix-shell --run 'echo load nix packages'
        working-directory: ./examples/bazel
      - name: First run of nix-shell to measure download time
        run: nix-shell --run 'bazelisk test //...'
        working-directory: ./examples/bazel
      - name: demo of multi-line command
        run: |
          nix-shell --run '
              echo "command 1"
              echo "command 2"
          '
        working-directory: ./examples/bazel
