name: examples

on: [push]

jobs:
  examples_bazel:
    runs-on: ubuntu-latest
    container: davidb31/nix-on-debian:latest
    steps:
      - uses: actions/checkout@v1
      - name: first run of nix-shell to measure download time
        run: nix-shell --run 'echo load nix packages'
        working-directory: ./examples/bazel
      - name: test and lint
        run: nix-shell --run 'bazelisk test //...'
        working-directory: ./examples/bazel
